### ISSUE TITLE
Lack compatibility of car types in server

### ISSUE THREAD

**Issue by KaspervanM** [KaspervanM/WiFiRC-Car#1]
## What
The hardware can change and the server interface should be able to deal with this.
You should be able to switch between modes of control.

## How
At least two modes should be added.

### Tank mode
* There are two motors for both sides of the vehicle.
* You steer by powering one engine more than the other.

### Car mode
* There is one engine for driving and one for steering
* You steer by making the steering motor turn the wheels.

## #Edit
The power of the steering engine in Car mode should not be variable.

**Comment by evanpacini** [comment]
I added both car and tank compatibility with joystick controls. The only thing left to do is to add WASD controls for car mode.
