### ISSUE TITLE
Joystick controls engine switch

### ISSUE THREAD

**Issue by KaspervanM** [KaspervanM/WiFiRC-Car#23]
## What
The joystick and the keys only work if the engines are set up correctly. This isn't always the case. Sometimes the engines are swapped or the wires are swapped. The person should be able to account for that in the interface.

## How
Add a settings tab with radio buttons or something similar. It should be able to reverse left and right and reverse + and -.

**Comment by evanpacini** [comment]
I've done that in the settings branch.
