### ISSUE TITLE
Connect RPI to WiFi without saving the SSID and password on the micro-sd chip.

### ISSUE THREAD

**Issue by KaspervanM** [KaspervanM/WiFiRC-Car#3]
## What
The RPI can connect to WiFi, but the SSID and password are stored in the 'wpa_supplicant.conf' file. This can easily be read and this shouldn't be the case.

## How
I am not sure yet. Perhaps using an external application to manage the connections can help.

**Comment by evanpacini** [comment]
This article from RPI community should help quite a bit:
[https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md](https://www.raspberrypi.org/documentation/configuration/wireless/wireless-cli.md)
