### ISSUE TITLE
Joystick controlls

### ISSUE THREAD

**Issue by KaspervanM** [KaspervanM/WiFiRC-Car#5]
## What
The controls are buttons now, but that is not very precise and _cannot_ be used on the phone. A joystick can be controlled with a mouse or with touchscreen. The power of the engines should change accordingly.

## How
* Replace the buttons with a 2D joystick (as seen in many mobile games): 
  * Large round background with a smaller circle which can be changed in position.
* The power to the engines should be changing according to the position of the circle in the background.

**Comment by evanpacini** [comment]
Perhaps we can use this one from github with MIT license:
[https://github.com/bobboteck/JoyStick](https://github.com/bobboteck/JoyStick)

**Comment by KaspervanM** [comment]
Sure, looks like a good place to start. We can perhaps also use it for the camera movement.

**Comment by evanpacini** [comment]
We need this to calculate values for both motors using the joystick:
[https://robotics.stackexchange.com/questions/2011/how-to-calculate-the-right-and-left-speed-for-a-tank-like-rover](https://robotics.stackexchange.com/questions/2011/how-to-calculate-the-right-and-left-speed-for-a-tank-like-rover)
